// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzorI01vitZfCop7Lfmh8O-N2FzVrv1Ow',
    appId: '1:1008505966544:android:0d6c0e5835054f16baf3d5',
    messagingSenderId: '1008505966544',
    projectId: 'demoapplication-6cad9',
    storageBucket: 'demoapplication-6cad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-LZxjH-v6fK2IbmbrP1FUtT551iUUB2c',
    appId: '1:1008505966544:ios:e412901267d5539cbaf3d5',
    messagingSenderId: '1008505966544',
    projectId: 'demoapplication-6cad9',
    storageBucket: 'demoapplication-6cad9.appspot.com',
    androidClientId: '1008505966544-mdgacqdn92vpgis5fc48gjhn8gvloroe.apps.googleusercontent.com',
    iosClientId: '1008505966544-1e0v29c8ac0155jjaivbfaauo7hoou1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapplicationDeep',
  );
}
